### ISSUE TITLE
Service.parseAddress: out of range error

### ISSUE THREAD

**Issue by vrothberg** [varlink/go#1]
We are currently facing a bug in Podman (i.e., libpod) described here: https://github.com/projectatomic/libpod/issues/888

`Service.parseError` ultimately leads to an out of range error when the passed string doesn't match the expected format (see https://github.com/varlink/go/blob/master/varlink/service.go#L199). I suggest using `net/url` for parsing strings, where `URI.Scheme` can be used to check the supported protocols etc.

**Comment by haraldh** [comment]
Fixed with commit 74025f30a00a57a6f32fd8bedc2552bc73e3ab48
