### ISSUE TITLE
Can not parse Systemd's varlink definitions

### ISSUE THREAD

**Issue by arianvp** [varlink/go#28]
I am not sure if this is a bug in your implementation or systemd not implementing the spec correctly

But systemd defines a varlink interface here:

https://systemd.io/USER_GROUP_API/

But  this library fails to parse it with the following error:

```
Error parsing file 'io.systemd.UserDatabase.varlink': unknown keyword ''
```

Trial and error seems to suggest this library is choking over the fact that `UserDatabase` is capitalized in the interface name. Are interface definitions not allowed to have capital letters in them? Or is this a bug in this library?

```
interface io.systemd.UserDatabase

method GetUserRecord(
        uid : ?int,
        userName : ?string,
        service : string
) -> (
        record : object,
        incomplete : bool
)

method GetGroupRecord(
        gid : ?int,
        groupName : ?string,
        service : string
) -> (
        record : object,
        incomplete : bool
)

method GetMemberships(
        userName : ?string,
        groupName : ?string,
        service : string
) -> (
        userName : string,
        groupName : string
)

error NoRecordFound()
error BadService()
error ServiceNotAvailable()
error ConflictingRecordFound()
error EnumerationNotSupported()

```

**Comment by arianvp** [comment]
Hunted down the issue for reference: https://github.com/systemd/systemd/issues/15952

**Comment by haraldh** [comment]
Also fixed python: https://github.com/varlink/python/pull/28
