### ISSUE TITLE
Please add copyright statement

### ISSUE THREAD

**Issue by onlyjob** [varlink/go#8]
As [required](https://github.com/varlink/go/blob/master/LICENSE#L178) by the LICENSE:

  https://github.com/varlink/go/blob/master/LICENSE#L189

Thanks.

**Comment by haraldh** [comment]
Does a global `COPYRIGHT` file work, too?

**Comment by onlyjob** [comment]
That's a possibility, yes.

**Comment by onlyjob** [comment]
Nice, thanks. Though IMHO it would have been better to do exactly what license recommends.
